### PR TITLE
Enhanced the presentation and language of the README

### PR DESCRIPTION
**Pull request by tvermaashutosh**
@roberto-butti 
I have improved the aesthetics as well as the language of the README.md file. Thereby, making it more attention grabbing and interesting.
I request you to kindly review my pull request and then merge it please.

### CODE REVIEW

**Review by roberto-butti — CHANGES_REQUESTED** [review]
Thank you for the Pull Request @tvermaashutosh . I really like the finetuning you did.
Amazing job!
Can I ask you to add also the `alt` attribute in the `img` tag , please? You can use the value on the `[]` in the previous markdown.

**Comment by tvermaashutosh** [comment]
@roberto-butti 
Sure! Let me do the changes just now.

**Comment by tvermaashutosh** [comment]
@roberto-butti 
I have make the required changes as per your request.

**Review by roberto-butti — APPROVED** [review]

**Comment by tvermaashutosh** [comment]
Are there any more changes required from my side @roberto-butti ?

**Comment by roberto-butti** [comment]
> Are there any more changes required from my side @roberto-butti ?

No more changes @tvermaashutosh  i,m going to merge this PR.
I like the new header of the readme. Thank you for your support!

**Pull request merged**
