### PR TITLE
Removed the empty bullet point and Improved the styling

### PR DESCRIPTION
**Pull request by Arcturus22**
I noticed an empty bullet point in the Changelog file, so I edited it. Also improved the styling by reducing the font size to make it look better.
Kindly review my PR and merge it.

### CODE REVIEW

**Comment by Arcturus22** [comment]
@roberto-butti 
Please review my PR, and if it is to your liking, please do merge it.

**Comment by roberto-butti** [comment]
hi @Arcturus22 , is there a specific and valuable reason to use the third level instead of the second level for the verdion in changelog?

**Comment by Arcturus22** [comment]
@roberto-butti 
Not really. It was not exactly looking good. When you look at the main heading Changelog having the first level and then immediately the second level, it wasn't making much contrast and wasn't giving more emphasis on the Changelog (as the heading).

Had there been text just after the Changelog heading, the others even with the second level would have made it look better. But as there wasn't any text, I changed the others to third level.

I can remove it if it's not to your liking.

**Comment by Arcturus22** [comment]
@roberto-butti Was the PR not upto the mark to be merged ?

**Comment by roberto-butti** [comment]
> @roberto-butti Was the PR not upto the mark to be merged ?

Yes, exactly, I prefer to have the release at the second level.
Thank you for all the PRs, I think you have the "gold medal" for the number of high-quality PRs opened and merged :)

**Comment by Arcturus22** [comment]
You flatter me. I'm glad I could contribute and help.

**Pull request closed without merging**
